### ISSUE TITLE
Forget to bump up the version number in __init__.py

### ISSUE THREAD

**Issue by bujyu-uo** [WistfulHopes/GBFRBlenderTools#19]
In 0.5.4, the version still shows 0.5.1 in blender plugin manger.

**Comment by AlphaSatanOmega** [comment]
That's just a blender bug. If you installed the addon without removing the older version first, it may show the old version number.
Can confirm I updated the version number for this update.

![image](https://github.com/WistfulHopes/GBFRBlenderTools/assets/44583573/7d94c8ce-2184-4bb4-9d44-f43ae9cca26e)
