### ISSUE TITLE
struct.error: unpack requires a buffer of 12 bytes

### ISSUE THREAD

**Issue by foursentup** [WistfulHopes/GBFRBlenderTools#32]
i used blender ver:4.2 and import model have this error, then i change ver:4.0.2 still have this error.
plugin ver1.1.0p2 or ver 1.0.0 i uesd cant fix it.
so sad :( 
![_6A J) HB2E20}9MA$2WPWJ](https://github.com/user-attachments/assets/321e6304-59ce-4557-8bbe-de2190016e10)

**Comment by AlphaSatanOmega** [comment]
What was the ID of the model you attempted to import?

**Comment by foursentup** [comment]
i find out the problem, dont put too many mesh in one folder
