### ISSUE TITLE
Submesh is not recognized.

### ISSUE THREAD

**Issue by rrtt2323** [WistfulHopes/GBFRBlenderTools#4]
![image](https://github.com/WistfulHopes/GBFRBlenderTools/assets/12709491/aaeceaf5-f84b-414a-9343-4e7466c46c40)
I'm having trouble importing Blender. 
Model UVs with Submesh are stacked together.

**Comment by rrtt2323** [comment]
After a brief test, I found that the reason was that I couldn't tell if it was SubMesh.
![image](https://github.com/WistfulHopes/GBFRBlenderTools/assets/12709491/d0c9a914-acc4-4fca-a771-1fda7832c151)
As a result, it was "False - 1".

**Comment by rrtt2323** [comment]
![image](https://github.com/WistfulHopes/GBFRBlenderTools/assets/12709491/1f3a09ae-7a25-40ba-af35-3614c6cfe02a)
I tried it and found it impossible to tell if it was a submesh or not.
Please, Is there a way to tell?

**Comment by AlphaSatanOmega** [comment]
You need to separate the model by materials. Most materials have their own texture that takes up the entire UV space.

Select the mesh > Go into edit mode > Press `Mesh` > `Separate` > `By Material`.

**Comment by AlphaSatanOmega** [comment]
Support issued through discord. Solution unchanged. Closing Issue.
