### ISSUE TITLE
[WinError 5] Access is denied

### ISSUE THREAD

**Issue by zineurysm** [WistfulHopes/GBFRBlenderTools#6]
![131cc60749035d0d300a5926b7782f12](https://github.com/WistfulHopes/GBFRBlenderTools/assets/161103778/e85341cb-0d19-4954-b752-f2cf26b33c33)
Importing the model went well enough, but exporting it gave me this error. Double checked to make sure the flatbuffers path was correct and everything. I obviously did something wrong, but I'm not sure what, hopefully can someone lend me a hand because I don't recall ever getting this problem exporting models from anything else. Thanks.

**Comment by AlphaSatanOmega** [comment]
Sometimes when the export fails, it'll leave files left over which don't get released by blender. Delete everything that was generated by the export in the folder you exported to. Then you should be able to export the model.

**Comment by zineurysm** [comment]
Did that, still getting the same error. I'm guessing the issue isn't with the addon and is an issue with python or another source...

**Comment by zineurysm** [comment]
Did that, still getting the same error. I'm guessing the issue isn't with the addon and is an issue with python or another source...

EDIT: accidentally didn't switch to unfinished.
